
/*
 * CreateMEMO.java
 *
 * Created on Oct 3, 2014, 9:09:50 PM
 */
package dailyplanner;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.ResultSet;
import java.sql.DriverManager;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class CreateMEMO extends javax.swing.JFrame {

    static final String JDBC_DRIVER="com.mysql.jdbc.Driver";
    static final String DB_URL="jdbc:mysql://localhost:3306/DailyPlanner";
    static final String USER="root";
    static final String PASS="prakhar";
    public static Connection conn=null;
    public static PreparedStatement ins=null,upd=null,seek=null;
    String user="",id="";
    int value;
    /** Creates new form CreateMEMO */
    public CreateMEMO(int a,String str1) {
        value=a;
        user=str1;
        initComponents();
    }
    public CreateMEMO(int a,String str1,String str2) {
        value=a;
        user=str1;
        id=str2;
        initComponents();
    }
    private CreateMEMO() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabeluname = new javax.swing.JLabel();
        jLabelpass = new javax.swing.JLabel();
        memo = new javax.swing.JTextField();
        datetime = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(-65536,true));
        jPanel1.setForeground(new java.awt.Color(-11400070,true));

        jPanel2.setBackground(new java.awt.Color(-16711681,true));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabeluname.setFont(new java.awt.Font("SansSerif", 2, 18));
        jLabeluname.setText("MEMO:");

        jLabelpass.setFont(new java.awt.Font("SansSerif", 2, 18));
        jLabelpass.setText("DATE & TIME:");

        datetime.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                datetimeFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelpass, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(datetime, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabeluname, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(memo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeluname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelpass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datetime, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        submit.setFont(new java.awt.Font("Dialog", 1, 14));
        submit.setText("SUBMIT");
        submit.setBorder(new javax.swing.border.SoftBevelBorder(0));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Dialog", 1, 14));
        back.setText("BACK");
        back.setBorder(new javax.swing.border.SoftBevelBorder(0));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        String Memo=memo.getText();
        String DateTime=datetime.getText();
        try{ 
            Class.forName(JDBC_DRIVER);
            conn=(Connection) DriverManager.getConnection(DB_URL,USER,PASS); 
            if(Memo.isEmpty())
            JOptionPane.showMessageDialog(rootPane, "MEMO Field Empty!!");
            else if("  -  -       :  ".equals(DateTime))
            JOptionPane.showMessageDialog(rootPane, "DATE Field Empty!!");
            else{
                if(value==1){
                   seek=(PreparedStatement)conn.prepareStatement("SELECT * FROM ToDo WHERE UName=? AND Memo=?");
                   seek.setString(1, user);
                   seek.setString(2, Memo);
                   ResultSet rstd=(ResultSet)seek.executeQuery();
                   if(rstd.next())
                   JOptionPane.showMessageDialog(rootPane, "Multiple Entries NOT Allowed!!");
                   else{
                       ins=(PreparedStatement)conn.prepareStatement("INSERT INTO ToDo VALUES(?,?,STR_TO_DATE(?,'%Y-%m-%d %H:%i:%s'))");
                       ins.setString(1, user);
                       ins.setString(2, Memo);
                       ins.setString(3, DateTime);
                       ins.executeUpdate();
                       JOptionPane.showMessageDialog(rootPane, "MEMO Created!!\nPlease Refresh");
                       this.setVisible(false);
                       ins.close();
                   }
                   rstd.close();
                   seek.close();
                }
                else{
                   upd=(PreparedStatement)conn.prepareStatement("UPDATE ToDo SET Memo=?,DateTime=STR_TO_DATE(?,'%Y-%m-%d %H:%i:%s') WHERE Memo=? AND UName=?");
                   upd.setString(1, Memo);
                   upd.setString(2, DateTime);
                   upd.setString(3, id);
                   upd.setString(4, user);
                   upd.executeUpdate();
                   JOptionPane.showMessageDialog(rootPane, "MEMO Updated!!\nPlease Refresh");
                   this.setVisible(false);
                   upd.close();
                }
            }
            conn.close();
          }catch (Exception ex) {
                    Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(rootPane, "Oops!! something went Wrong!!CreateMEmo"); 
           }
}//GEN-LAST:event_submitActionPerformed

private void datetimeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_datetimeFocusGained
    if(datetime.getText().equals("YYYY-MM-DD hh:mm:ss"))
    datetime.setText("");
}//GEN-LAST:event_datetimeFocusGained

private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
    this.setVisible(false);
}//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateMEMO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateMEMO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateMEMO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateMEMO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
        
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField datetime;
    private javax.swing.JLabel jLabelpass;
    private javax.swing.JLabel jLabeluname;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField memo;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables

        public void display(String str1,String str2){
            /*if(value==2){
                int len=str2.length();
                str2=str2.substring(0,len-2);
            }*/
            memo.setText(str1);
            datetime.setText(str2);
        }
 }
